### ISSUE TITLE
Typos in code & doc for word `probability`

### ISSUE THREAD

**Issue by masoodrb** [janet-lang/spork#105]
There seem to be a typo in the function `math/check-propability` which should be `math/check-probability` and the documentation of the function `math/binominal-distribution` which should also be `probability` instead of propability.

**Comment by sogaiu** [comment]
I think you're prop^Hbably right about those things: https://github.com/janet-lang/spork/blob/465d489389cb093cc474379772fa52691819c6c2/spork/math.janet#L363-L369

**Comment by pepe** [comment]
Oh. That would be me :-)

**Comment by sogaiu** [comment]
Does a PR seem welcome for this?

Change of name in a function does present an issue of compatibility but may be it hasn't been too long since this got added?

**Comment by pepe** [comment]
If you have spare moments, please do. No one except me used it :-D, so the change would not be such an issue.

**Comment by masoodrb** [comment]
I suppose there is a high chance that if there was a user of this function they would have noticed the typo. I was just going through the docs because I was bored.

**Comment by sogaiu** [comment]
I hope the reading was entertaining :)

Would you like to do a PR?

If not, I can work on one.
