### ISSUE TITLE
timeit loop?

### ISSUE THREAD

**Issue by primo-ppcg** [janet-lang/spork#127]
I've recently created a short macro for profiling various changes, and thought it might be a good addition to spork. While poking around looking for an appropriate place to add it, I found that it already exists: [test/timeit](https://github.com/janet-lang/spork/blob/master/spork/test.janet#L59-L73)

Which is shockingly similar to what I wrote independently:
```janet
(defmacro timeit
  ``Similar to `loop`, but outputs performance statistics after completion.``
  [head & body]
  (with-syms [clk cnt elp run]
    ~(do
       (var ,cnt 0)
       (def ,clk (os/clock))
       (loop ,head (++ ,cnt) ,;body)
       (def ,elp (- (os/clock) ,clk))
       (def ,run (/ ,elp ,cnt))
       (cond
         (< ,run 1e-3) (printf "elapsed %fs, %.4gµs/body" ,elp (* ,run 1_000_000))
         (< ,run 1) (printf "elapsed %fs, %.4gms/body" ,elp (* ,run 1_000))
         (printf "elapsed %fs, %.4gs/body" ,elp ,run)))))
```
The primary difference is that this implementation piggy-backs off of the loop macro, and can give per body averages, where the current implementation executes a single form.

Current implementation:
```janet
(def ind (range 2000))
(timeit
  (repeat 5_000_000
    (take -1000 ind)))
# ->
Elapsed time: 2.03609 seconds
```

Above implementation:
```janet
(def ind (range 2000))
(timeit [:repeat 5_000_000]
  (take -1000 ind))
# ->
elapsed 2.025604s, 0.4051µs/body
```
which I find to be more useful, and could possibly make a good replacement / update / parallel function.

**Comment by pepe** [comment]
We can have both implementations in the spork, as someone can use the current version.

**Comment by primo-ppcg** [comment]
Cleaned up slightly:

```janet
(defmacro timeit-loop
  ``Similar to `loop`, but outputs performance statistics after completion.``
  [head & body]
  (def tag "Elapsed time:")
  (with-syms [start c elapsed per-body]
    ~(do
       (var ,c 0)
       (def ,start (os/clock))
       (loop ,head (++ ,c) ,;body)
       (def ,elapsed (- (os/clock) ,start))
       (def ,per-body (/ ,elapsed ,c))
       (cond
         (< ,per-body 1e-3) (printf "%s %fs, %.4gµs/body" ,tag ,elapsed (* ,per-body 1_000_000))
         (< ,per-body 1) (printf "%s %fs, %.4gms/body" ,tag ,elapsed (* ,per-body 1_000))
         (printf "%s %fs, %.4gs/body" ,tag ,elapsed ,per-body)))))
```

Two things I'd like to modify:
- add a `:timeout` verb to prematurely break after a given number of seconds has elapsed
- make `tag` somehow configurable, as it is with `timeit`
I'm not quite sure what the best approach is to achieve either of these. Suggestions welcome.

**Comment by sogaiu** [comment]
No good ideas about `:timeout`.

Couple of hacky ideas for `tag`:

1. Dynamic variable
2. Scan first part of body for a keyword to use as a tag

**Comment by primo-ppcg** [comment]
> No good ideas about `:timeout`.

Patching it for an `:iterate` verb seems to work.

I suppose if the first form of the body is a `bytes?`, it could be assumed to be the tag?

**Comment by sogaiu** [comment]
> Patching it for an :iterate verb seems to work.

Nice.

> I suppose if the first form of the body is a bytes?, it could be assumed to be the tag?

That sounds like it might work [1].

If you ever wanted to support more / other things, a struct (no point in it being a table I guess) could be checked for perhaps.

---

[1] This kind of approach has been working for me in other places.  One example is for ["tagging" jpm tasks](https://github.com/sogaiu/jpm-tasks-view#jpm-tasks-view-jptv).  There I look for a keyword followed by a tuple -- after `(task "name" [...]`.  `timeit-loop`'s case is safer because you control it :)

**Comment by primo-ppcg** [comment]
> Patching it for an `:iterate` verb seems to work.

This is actually a really bad idea. From the performance stats, this is primarily timing the `os/clock` function. Seems like a `os/sleep` would need to be run in a separate thread.

**Comment by primo-ppcg** [comment]
> That sounds like it might work [1].

I think it works great.
```janet
(defmacro timeit-loop
  ``Similar to `loop`, but outputs performance statistics after completion.
  Additionally defines a `:timeout` verb to iterate continuously for a given
  number of seconds. If the first form of `body` is a bytes, it will be taken
  as a custom tag.``
  [head & body]
  (var tag "Elapsed time:")
  (def head2 @[;head])
  (def body2 @[;body])
  (with-syms [c start elapsed per-body]
    (when (def i (index-of :timeout head2))
      (array/insert head2 i [])
      (set (head2 (+ i 1)) :iterate)
      (set (head2 (+ i 2)) ~(< (- (os/clock) ,start) ,(in head2 (+ i 2)))))
    (when (bytes? (get body2 0))
      (set tag (in body2 0))
      (array/remove body2 0))
    ~(do
       (var ,c 0)
       (def ,start (os/clock))
       (loop ,head2 (++ ,c) ,;body2)
       (def ,elapsed (- (os/clock) ,start))
       (def ,per-body (/ ,elapsed ,c))
       (cond
         (< ,per-body 1e-3) (printf "%s %.3fs, %.4gµs/body" ,tag ,elapsed (* ,per-body 1_000_000))
         (< ,per-body 1) (printf "%s %.3fs, %.4gms/body" ,tag ,elapsed (* ,per-body 1_000))
         (printf "%s %.3fs, %.4gs/body" ,tag ,elapsed ,per-body)))))

(timeit-loop [:repeat 200_000_000] ":repeat ")
(timeit-loop [:timeout 1] ":timeout")
# ->
:repeat  1.043s, 0.005214µs/body
:timeout 1.000s, 0.03572µs/body
```

About the `:timeout`, the `os/clock` adds about 0.03µs of overhead, which probably isn't a big deal for the purpose of comparison, but also seems like it could be avoided using an `os/sleep` in a separate thread?

**Comment by sogaiu** [comment]
Tried it out a bit:

```janet
  (do
    (def ds @{})
    (timeit-loop [:repeat 100_000] :label
      (put ds :a 1))
    ds)
  # printed: label 0.008s, 0.08157µs/body
  # =>
  @{:a 1}

  (do
    (def ds @{})
    (timeit-loop [:repeat 100_000] :label
      (set (ds :a) 1))
    ds)
  # printed: label 0.007s, 0.07186µs/body
  # =>
  @{:a 1}

  (timeit-loop [:timeout 1] :label
    (get {:a 1} :a))
  # printed: label 1.000s, 0.06712µs/body
  # =>
  nil
```

Looks like it's working :)

> seems like it could be avoided using an os/sleep in a separate thread?

I'm not sure, but may be at 0.03µs, it's better to keep the implementation simple at least initially?

**Comment by primo-ppcg** [comment]
> I'm not sure, but may be at 0.03µs, it's better to keep the implementation simple at least initially?

Agreed.

**Comment by primo-ppcg** [comment]
> I'm not sure, but may be at 0.03µs, it's better to keep the implementation simple at least initially?

Actually [ev/deadline](https://janet-lang.org/api/index.html#ev/deadline) or [ev/with-deadline](ev/with-deadline) seem like they were intended for precisely this sort of thing. I can't figure out the proper usage, though.

```janet
(ev/with-deadline 1 (forever))
```
This never terminates.

**Comment by sogaiu** [comment]
Similar situation here.

Replacing `(forever nil)` with `(os/sleep 3)` seems to work though.

Admittedly, not so helpful for the intended use-case.

**Comment by bakpakin** [comment]
Janet has a way to interrupt the interpreter, but it's not accessible from Janet, only from C with janet_interrupt. You could insert (ev/sleep 0) every turn of the loop but that would have unacceptable perf cost for timing.

Ideal we could spawn a new thread, sleep for some time, and then set the interrupt flag in the original interpreter.

**Comment by primo-ppcg** [comment]
The task doesn't seem so complicated, though.
1. Start a thread.
2. Terminate it after `seconds`.

Everything I tried either fails to halt the thread, or terminates with a seemingly unrecoverable error.

**Comment by bakpakin** [comment]
True, there is some room for some more functionality in the ev library here - both the ability to   Send interrupts to other threads as well as just call pthread_cancel on them. Unfortunately this has some issues with memory management so we may not support pthread_cancel directly
