### ISSUE TITLE
Add chance to set the HTTP status in httpf

### ISSUE THREAD

**Issue by pepe** [janet-lang/spork#156]
I already tried httpf on several projects and like the design choices. Yet, I am missing a chance to set the HTTP status code in the handler. Would you accept the PR with a mechanism similar to how response headers are set in the current version with a dynamic?

**Comment by bakpakin** [comment]
Yes, that would be reasonable if it becomes much easier to use. However, I think the request method is available in the parsed header (from spork/http.janet).

**Comment by pepe** [comment]
Thanks. I am unsure what you mean by the method's availability, but I will prepare PR for the HTTP status code ASAP.
