### ISSUE TITLE
Curious code in `math.janet`

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#176]
I noticed [this line](https://github.com/janet-lang/spork/blob/7a4eff4bfb9486a6c6079ee8bb12e6789cce4564/spork/math.janet#L1347), [this line](https://github.com/janet-lang/spork/blob/7a4eff4bfb9486a6c6079ee8bb12e6789cce4564/spork/math.janet#L1305), and [these lines](https://github.com/janet-lang/spork/blob/7a4eff4bfb9486a6c6079ee8bb12e6789cce4564/spork/math.janet#L1227-L1228) in `math.janet`:

```janet
  (def one (+ (- n n) 1))
```

```janet
  (def zero (- n n))
```

```janet
  (var d (- n 1))
  (def one (- n d))
```

Are these special optimization tricks @primo-ppcg?

**Comment by primo-ppcg** [comment]
Yes, these eliminate the need for polymorphic comparators, because `one` and `n` are of the same type.

**Comment by sogaiu** [comment]
Thanks for the explanation!

**Comment by primo-ppcg** [comment]
I suppose dynamic coercion might also be something of a lexical gap.

```janet
(def one (coerce 1 (type n)))
```

The intent would be a lot more clear.
