### ISSUE TITLE
Segfault if `rawterm/getch` is called without calling `rawterm/begin` first

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#198]
Calling `rawterm/getch` without having first called `rawterm/begin` leads to a segfault here (Void Linux):

```
$ janet
Janet 1.36.0-88e60c30 linux/x64/gcc - '(doc)' for help
repl:1:> (do (import spork/rawterm) :loaded)
:loaded
repl:2:> (rawterm/getch)
Segmentation fault
```

Is it practical to have a non-fatal error instead?

---

Spork was at commit 1c081c7f.

**Comment by pepe** [comment]
It is more than practical :-D

**Comment by sogaiu** [comment]
Thank you!
