### ISSUE TITLE
spork/fmt silently converts "paren" arrays to "bracket" arrays

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#20]
Paren arrays appear to be converted to bracket arrays:

https://github.com/janet-lang/spork/blob/714c216ac7f7fb13ece2d9735fa608f1962874e2/spork/fmt.janet#L45

https://github.com/janet-lang/spork/blob/714c216ac7f7fb13ece2d9735fa608f1962874e2/spork/fmt.janet#L160

Perhaps there is no obvious drawback.  It also seems straight-forward to preserve the distinction.

Any reason for the current behavior?

**Comment by bakpakin** [comment]
They are converted for uniformity, unlike tuples, brackets vs parents for arrays are completely identical in behavior in all cases. I prefer brackets.

**Comment by sogaiu** [comment]
Thanks for the explanation.
