### ISSUE TITLE
spork/fmt/format-print does not align elements in quoted tuples

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#25]
Elements of quoted tuples are not left-aligned when passed through `format-print`:
```
repl:2:> (spork/fmt/format-print "'(:a\n:b\n:c)")
'(:a
   :b
   :c)
```
Elements of bracket tuples become aligned:
```
repl:3:> (spork/fmt/format-print "[:a\n:b\n:c]")
[:a
 :b
 :c]
```
May be this is intentional?

If so, I would like to understand why.  Any hints?

**Comment by pyrmont** [comment]
I've only glanced at the code but I don't think it's intentional; it's just there's no code at the moment that detects whether a form is quoted (and so is to be treated like a bracketed tuple). I think it would be cool if this were added, though.

**Comment by sogaiu** [comment]
Some speculation is that the current implementation allows the use of parens in the construction of code inside macros while having indentation more suited to code.

If constructing "data" that isn't really representing code, perhaps it's better to just use square bracket tuples and get an alternate indentation style.

If these points summarize the current situation, it seems worth spelling this out somewhere.  May be it is already?

**Comment by bakpakin** [comment]
It's been a while, but nothing has change so I will answer this.

fmt treats any tuple with parens and the first element on it's own line as a "block" form, like `do` - (well, any form that doesn't start with another recursive data structure). And yes, we don't try and deduce from other contextual information like the quote that this is not a piece of code.

**Comment by sogaiu** [comment]
Thanks for the explanation.
