### ISSUE TITLE
contribution guidelines for adding multi-file modules/libraries?

### ISSUE THREAD

**Issue by uvtc** [janet-lang/spork#26]
It looks to me like spork currently contains only single-file modules. However, some modules that may be a good fit for inclusion into spork may contain multiple files, their own tests, docs, etc. It is not clear how one would create a PR for inclusion of modules/libraries of this type. Would it make sense for there to be a contributions doc for this repository, specifically including guidelines for how to weave in these kinds of "larger" libraries?

**Comment by uvtc** [comment]
One that came to mind is [tomlin](https://github.com/pyrmont/tomlin).

**Comment by uvtc** [comment]
Or is spork better kept simple and for single-file modules?

**Comment by bakpakin** [comment]
Currently, I think spork is best served by smaller, janet only modules. One reason for this is adding C modules means it may be harder to install in some platforms, but I'm not making a hard line here.

**Comment by pepe** [comment]
Thank you very much for the answer. I will link the answer to the spork discussion.

**Comment by pepe** [comment]
I guess we can close this, @uvtc.

**Comment by uvtc** [comment]
Yup. Thanks.
