### ISSUE TITLE
Additional candidates for indenting-by-2 (label, prompt)

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#30]
The docstring for `indent-2-forms` in `spork/fmt` [currently says](https://github.com/janet-lang/spork/blob/b3e8b31454cb56e6d07973fa77121280a08cbe21/spork/fmt.janet#L77):

> "A list of forms that are control forms and should be indented two spaces."

Would it make sense to add `label` and `prompt`?

**Comment by bakpakin** [comment]
Yes, those would make sense as such forms. There might a few others missing as well.

**Comment by sogaiu** [comment]
May be `compwhen` too?

https://github.com/janet-lang/janet/blob/83f7de33c0b9c71eb6c0c8c51a9480e51565203a/src/boot/boot.janet#L2979-L2986
