### ISSUE TITLE
Test suite

### ISSUE THREAD

**Issue by pepe** [janet-lang/spork#5]
Are you considering the addition of the test suite? If so, may I try to do it?

I will use tester helper from your other libraries, and I will try to follow your test philosophy.

**Comment by bakpakin** [comment]
Feel free to add tests here - There aren't many simply because I haven't gotten to it. Tests are always welcome!

**Comment by pepe** [comment]
Thank you! I will try.

**Comment by pepe** [comment]
So I added first two (easier ones) suites, please can you check if it LGTY?

**Comment by pepe** [comment]
Closed in #6
