### ISSUE TITLE
generate and upload spork docs?

### ISSUE THREAD

**Issue by uvtc** [janet-lang/spork#64]
It would be useful if the spork docs (rendered as html by mendoza) were available on or linked to from the Janet website.

Is there any way I can help?

**Comment by bakpakin** [comment]
It would be nice indeed. GitHub pages is a nice way to host docs. While it would be cool to have library docs (like for spork) and Janet-lang.org proper, I suspect it might be too difficult to be worth the effort, both to setup and maintain.

**Comment by bakpakin** [comment]
Spork docs are now periodically uploaded to https://janet-lang.org/api/spork/index.html

Much of the prose in the `doc` directory needs to be moved into janet-lang/janet-lang.org, but API level documentation is auto-generated.
