### ISSUE TITLE
netrepl not working because of missing rawterm

### ISSUE THREAD

**Issue by paines** [janet-lang/spork#90]
After installing spork via `sudo jpm install https://github.com/janet-lang/spork.git` and then adding `(import spork/netrepl)` to my testfile I get 
```
janet horace.janet 
error: could not find module spork/rawterm:
    /usr/local/lib/janet/spork/rawterm.jimage
    /usr/local/lib/janet/spork/rawterm.janet
    /usr/local/lib/janet/spork/rawterm/init.janet
    /usr/local/lib/janet/spork/rawterm.so
  in require-1 [boot.janet] on line 2901, column 20
  in import* [boot.janet] on line 2940, column 15
  in _thunk [/usr/local/lib/janet/spork/getline.janet] (tailcall) on line 10, column 1
  in dofile [boot.janet] (tailcall) on line 2878, column 7
  in source-loader [boot.janet] on line 2889, column 15
  in require-1 [boot.janet] on line 2909, column 18
  in import* [boot.janet] (tailcall) on line 2940, column 15
  in dofile [boot.janet] (tailcall) on line 2878, column 7
  in source-loader [boot.janet] on line 2889, column 15
  in require-1 [boot.janet] on line 2909, column 18
  in import* [boot.janet] on line 2940, column 15
  in _thunk [horace.janet] (tailcall) on line 3, column 1
```
It looks like there was a rawterm.a build, but not a rawterm.so...

**Comment by bakpakin** [comment]
What OS and janet version are you using? If the static library is built I don't see why the .so would not be built.

Also worth making sure you haev an up to date jpm with `sudo jpm install jpm`

**Comment by bakpakin** [comment]
Also the output of `jpm show-paths` should have modpath as `/usr/local/lib/janet`, according to your stacktrace. If it doesn't, it may be that rawterm.so was installed somewhere else and jpm/janet is configured incorrectly

**Comment by paines** [comment]
After updating jpm and installing sprok again this issue is gone. Thanks for your support.

**Comment by paines** [comment]
Sorry for reopening!

Maybe I have misunderstood what netrepl is supposed to do or supposed to be used for. I want to develop a game interactivly and have some code:

```
(use jaylib)

(import spork/netrepl)

(defn draw []
  (let [[x y] (get-mouse-position)]
    (draw-circle-gradient (math/floor x) (math/floor y) 31.4 :lime :red)
    (draw-poly [500 200] 5 40 0 :magenta)
    (draw-line-bezier
      [(- x 100) y]
      [(+ x 100) (+ y 50)]
      4 :pink)
    (draw-line-ex
      [x (- y 10)]
      [x (+ y 10)]
      4 :sky-blue)
    (draw-line-strip
      [[x 0] [x 100] [50 y] [10 180]]
      :ray-white)))

(netrepl/server-single)

(init-window 1024 768 "Test Game")
(set-target-fps 60)
(hide-cursor)

(while (not (window-should-close))
  (begin-drawing)
  (clear-background [0 0 0])
  (draw)
  (end-drawing))

(close-window)
```

So jaylib is setup, there is a window and a proper drawing loop . I also started a netrepl which should wait on incoming connections. Now I would telnet localhost port 9365 and update the draw function (again and again), and see my changes. So the plan. Maybe it would need some locking before updating the drawing, but in theory the plan should work. But netrepl seems not to evaluate anything. Also I tried the netrepl/client but the effect is the same.

**Comment by bakpakin** [comment]
Yeah, a lot of confusion here.

First, you would need to run the net repl server on a client in a new fiber, for example with (ev/spawn …). And yes, since jaylib is blocking there is some latency but in practice this should actually work alright - at 60fps, requests will have 16ms latency. Still, not ideal but not a deal breaker.

second, telnet is not anything you want here, the netrepl protocol requires a real client. ‘janet-netrepl -c’ is the command you would use to connect.
