### ISSUE TITLE
Test fails on Windows 10: file copied with sh/copy-file is not the same

### ISSUE THREAD

**Issue by sogaiu** [janet-lang/spork#96]
The following test is failing for me on Windows:

https://github.com/janet-lang/spork/blob/63f656e6f41b469b484903373187e96616eac837/test/suite0017.janet#L24-L26

Investigating a bit, `test2.file` seems to end with a CR byte while `test.file` does not.

As a side note, the test works fine for me on a Linux box.

**Comment by tionis** [comment]
This is probably due to git adding the CR byte on checkout, I'd like to test this, but don't have a working jpm setup on my windows machine.

**Comment by sogaiu** [comment]
In a different repository I had added this: https://github.com/sogaiu/judge-gen/blob/master/.gitattributes

Does that seem like the kind of thing you had in mind for testing?

**Comment by tionis** [comment]
To be honest, I not really sure. I would have to experiment with it myself. But if that works and doesn't break anything else ok the project, it should be fine I think?
Maybe this should be applied to all static test files then?

**Comment by sogaiu** [comment]
@tionis

I looked into the situation a bit more.

If `test.file` doesn't have any line ending characters, the test seems to work fine.

If `test.file` ends with a newline character, the test fails and it looks like `test2.file` has both a carriage return and a newline character at the end.

The `:w` in the `file/open` of `make-new-file` may be a factor:

https://github.com/janet-lang/spork/blob/63f656e6f41b469b484903373187e96616eac837/spork/sh.janet#L95-L104

Chaging the mode to `:wb` made the test pass.

---

On a side note, it doesn't look like `make-new-file`'s optional parameter `mode` is used anywhere.

**Comment by tionis** [comment]
I see, I completely forgot about the existence of the binary flag for file/open

**Comment by sogaiu** [comment]
@tionis

Regarding `sh/make-new-file` and the `mode` argument, I filed #98.

Perhaps a straight-forward fix would be to make `file/open`'s second argument `mode`.

So:

```janet
(file/open file-path :w)
```

would become:

```janet
(file/open file-path mode)
```

If that seems appropriate, perhaps the line in `sh/copy-file`:

https://github.com/janet-lang/spork/blob/63f656e6f41b469b484903373187e96616eac837/spork/sh.janet#L113

can specify a different mode, say `:wb`, to address this issue.

How does that seem?

**Comment by tionis** [comment]
Perhaps an additional keyword argument :mode for the file creating functions would be useful instead.

**Comment by sogaiu** [comment]
By "keyword argument", do you mean this sort of thing? https://janet-lang.org/docs/functions.html#Keyword-style-arguments

**Comment by tionis** [comment]
Yes, exactly, functions using optional arguments with Keywords can be extended later, without breaking previous code and also allow specifying only one select optional argument. While only one would have to be added here, it would be easier to extend later.
I'm curious what others think about this argumentation.

**Comment by sogaiu** [comment]
For `sh/make-new-file`, it looked like in https://github.com/janet-lang/spork/commit/ae9db3d5c953d54a0cca74f9352db160e749fce9, @bakpakin intended for an ordinary optional argument.  May be he'd be fine with a keyword argument though.

**Comment by tionis** [comment]
Not really, when I find time I will go over the current sh.janet in detail. I find the namespace currently a bit unorganized

**Comment by sogaiu** [comment]
bakpakin merged #99 and I verified that the change described in https://github.com/janet-lang/spork/issues/96#issuecomment-1368435068 works on a Windows machine and a Linux machine.

Will make a PR.

**Comment by sogaiu** [comment]
The test passes for me now.
